#! /bin/sh

bspc config border_width        2
bspc config top_padding		32
bspc config window_gap         	15
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V
#bspc rule -a Gimp desktop=^8 follow=on floating=on


#use the defined colors
#bspc config <example> ${color_name}


#autostart
panel &
