#! /bin/sh


#FONT="Noto Sans:size=10"
FONT="Inconsolata:size=10"

export FONT


if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &

#clock
while true; do
	echo -e "TIME$(date "+%H:%M")"
	
	sleep 5
done > "$PANEL_FIFO" &


. panel_colors


cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$FONT" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &


wait
